services:
  - type: web
    name: novixgames
    env: node
    plan: free
    envVars:
      - key: SUPABASE_URL
        value: ""
      - key: SUPABASE_KEY
        value: ""
      - key: SESSION_SECRET
        value: ""
    buildCommand: pnpm install
    startCommand: pnpm start
